apiVersion: v1 
kind: Service
metadata:
  name: preview-service
spec:
  selector:
    purpose: blue-green
    project: roboshop
    colour: green
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80